import './globals.css'
import { Inter } from 'next/font/google'
import {useUser} from "@/lib/hooks/useUser";
import {Profile} from "@/app/components/Profile";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const {getCurrentUser} = useUser()
  const {error, user} = await  getCurrentUser()

  return (
    <html lang="en">
      <body className={inter.className}>
      <header>
        <nav className={"flex justify-between items-center p-8"}>
          {user === null ? (
            <div className={"text-red-500"}>
              No Logged in app
            </div>
          ) :
              <Profile name={user?.email ?? ""} email={ user?.email ?? ""} />
          }
        </nav>

      </header>
       {children}
      </body>
    </html>
  )
}
